### PR TITLE
Moved function descriptions to .cpp from .h

### PR DESCRIPTION
**Pull request by sihsob**
Moved the function descriptions in the .h file to the .cpp file and added a documentation header at the top of clean.cpp.  Also adjusted the styling of documentation on diffNaive.cpp

### CODE REVIEW

**Comment by kmcnellis** [comment]
I like the changes, but maybe keep the function descriptions in both places?  That way a user can quickly look through the list of available functions in the header and figure out how to use them and what arguments are needed.

**Comment by kmcnellis** [comment]
Also, this should be merged into develop, not master

**Comment by sihsob** [comment]
Okay I'll make those changes. I was just following the styling guide which said put the comments right  where it's actually implemented, but I can add them back. Also sorry about making the push to master. I wasn't sure where to push to and I realized after that it should probably have been to develop.

**Comment by kmcnellis** [comment]
Thats ok!  I've also clarified the style guide for that.

**Pull request closed without merging**
