### PR TITLE
Logout button

### PR DESCRIPTION
**Pull request by V1ct0r-SLiNv-Zhu**
Basic HTTP Authentication is an ancient(15+ -year-old) auth method that
wasn't designed to manage logging out. Thus the only way to log out is
closing the browser(not only the current tab). There are some
hacks/workaround online but they are not comprehensively compatible to
different browsers or OS.

For now I am just adding a pop up script to reminds users to close the
browser if they want to log out or don't want their submission to be
messed by evil roommates.

If in the future we want a "real" logout functionality, we have to
switch to a session-aware authentication protocol.

**This is also related to Issue #76.
link: https://github.com/RCOS-Grading-Server/HWserver/issues/76

### CODE REVIEW

**Comment by MasterOdin** [comment]
You can get "pseudo" logout behavior though using a $_SESSION variable.

Here's a code block:
```
session_start();
if (isset($_GET['logout'])) {
    session_destroy();
    echo "Logged out";
    exit();
}
if (!isset($_SESSION['logged_in'])) {
    $_SESSION['logged_in'] = false;
else {
    if (isset($_SERVER['PHP_AUTH_USER'])) {
        $user = $_SERVER['PHP_AUTH_USER'];
        $_SESSION['logged_in'] = true;
    } else if (isset($_SERVER['REMOTE_USER'])) {
        $user = $_SERVER['PHP_AUTH_USER'];
        $_SESSION['logged_in'] = true;
    }
}

if (!$_SESSION['logged_in']) {
    header('WWW-Authenticate: Basic realm=HWServer'); 
    header('HTTP/1.0 401 Unauthorized'); 
    exit;
}

// rest of index.php
```

**Comment by V1ct0r-SLiNv-Zhu** [comment]
@MasterOdin Did you test the code? I have seen that on some websites already, didn't get it working. Also it has to work for at least IE, Chrome, and Firefox.

**Comment by MasterOdin** [comment]
It worked well enough for me on my development box that runs Ubuntu + Chrome. This'll work on any browser worth supporting as it's basic PHP code.

**Comment by V1ct0r-SLiNv-Zhu** [comment]
@MasterOdin After testing with IE 11, Chrome, Firefox on Win7 + Win8, it works for Chrome and Firefox but not IE 11. 
Problem with IE: If you log in, then try logging out. It works if you try to go back or revisit http://hwserver/?course=csci1200 for the first time; by canceling the dialog login box and refresh or visit the home page again, you're back to logged in status.

On the other hand, it's called "pseudo" anyways, but it is a fairly good temporary way to do it. Thanks for point this out~

**Comment by MasterOdin** [comment]
There's really no fix then for IE if it's not unsetting $_SERVER['PHP_AUTH_USER'] when you hit cancel on the box.

Could use [get_browser](http://php.net/manual/en/function.get-browser.php) or the JS equivalent to display an alert to only IE users about this, but as is, this is probably as good as you'd get without getting some access to the LabStaff authentication to do via pure PHP.

**Pull request merged**
